### ISSUE TITLE
Game crashes when player/bot receives damage

### ISSUE THREAD

**Issue by ElGhoust** [Cookie-K/GTFO-CinematographyPlugin#3]
## Video Report
[Youtube | CinematographyPlugin 1.2.6 - OnIncomingDamage Crash](https://www.youtube.com/watch?v=ZWIcOHkoNN4)

## Context
Following the release of the ALT://R3 update, the game crashes when a player or a bot receives damage from any source. It seems like the developers have made some changes to the `OnIncomingDamage(..)` method.

From what I gathered on the discord server, these changes also affected other mods. Modders managed to solve the issue by either commenting the problematic code (ChatterReborn), or by fixing/rewriting the patch related to the method (CConsole used to crash the same way and I think they fixed it by using a [native detour](https://discord.com/channels/782438773690597389/783918553626836992/1084493247411409026)).

## Process
**CinematographyPlugin Version:** 1.2.6
**Game Version:** Starting from the release of ALT://R3, up to the recent patches

This crash has been observed on my two PCs, and on a friend's PC.
It is easily reproduced by following these steps :
- Launch the game with the plugin installed
- Drop in any level
- Take damage (fall damage, any ennemy attack, friendly-fire...) --> Game crashes instantly

The following logs are written in **.\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\\<profile_name>\BepInEx\ErrorLog.log** after the crash :
```log
Setting breakpad minidump AppID = 493520
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198048097107 [API loaded no]
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Il2CppInterop.Runtime.IL2CPP.il2cpp_value_box(IntPtr, IntPtr)
--------------------------------
   at DynamicClass.(il2cpp -> managed) OnIncomingDamage(il2cpp -> managed) OnIncomingDamage(IntPtr, Single, Single, IntPtr, Il2CppInterop.Runtime.Runtime.Il2CppMethodInfo*)

```

## Temporary workaround
By disabling the `Prefix_IgnoreAllDamage(..)` patch related to the problematic method and rebuilding the DLL, the bots and players can receive damage again without the game crashing. 

![commented code](https://user-images.githubusercontent.com/35735422/228966328-7a93e2b9-1fcf-46ce-b9d9-75794bded35b.png)

Though, it does mean the player controlling the camera can get killed. The workaround is to use Godmode from other mods like CConsole, where the equivalent patch has been fixed.

**Comment by Cookie-K** [comment]
Thanks for letting me know. I've just opted to give the camera man a huge amount of health when in the camera mode.
